"""description of migration

Revision ID: 217b3eedd3b0
Revises: 
Create Date: 2023-03-29 20:52:11.703733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217b3eedd3b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('activities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('liked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='activities_pkey')
    )
    op.drop_table('activity')
    # ### end Alembic commands ###
